---
- hosts: httpd
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start httpd service
      service: 
        name: httpd
        state: started
        enabled: true
