---
- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
- name: update permission on docker-compose
  command: chmod +x /usr/local/bin/docker-compose