---
- name: installa deependency 
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add the GPG key for the official Docker repository 
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the Docker repository to APT
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

-  name: update system packages
   apt:
    update_cache: yes

- name: installa docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes

