---
- hosts: psql_db
  tasks:
    - name: start firewall
      service:
        name: firewalld
        state: started
        enabled: true

    - name: install yum utils
      yum:
        name: yum-utils
        state: present
    - name: copy nginx.repo data to /etc/yum.repos.d/
      copy:
        src: /home/avinash/itversity/task2/work/repo_data/nginx.repo
        dest: /etc/yum.repos.d/nginx.repo

    - name: install nginx
      yum:
        name: nginx
        state: latest
    - name: allow nginx through firewall
      firewalld:
        service: http
        state: enabled
        permanent: yes

    - name: firewall reload
      service:
        name: firewalld
        state: reloaded

    - name: start nginx service
      service:
        name: nginx
        state: started
        enabled: true
