---
- hosts: httpd
  tasks:
    - name: start firewall
      service: 
        name: firewalld
        state: started
        enabled: true
    - name: set timezone
      shell: timedatectl set-timezone Asia/Kolkata

    - name: Install NTP
      yum: 
        name: ntp 
        state: latest
    - name: start ntp
      service:
        name: ntpd
        state: started
        enabled: true 

    - name: Copy over the NTP configuration
      template: src=/home/avinash/itversity/task2/work/ntp_data/ntp.conf dest=/etc/ntp.conf

    - name: restart ntpd
      service:
        name: ntpd
        state: restarted
        enabled: true


    - name: allow ntp through firewall
      shell: firewall-cmd --add-service=ntp --permanent

    - name: firewall reload
      shell: firewall-cmd --reload

      
 
- hosts: mysql_db
  tasks:
    - name: start firewall
      service:
        name: firewalld
        state: started
        enabled: true

    - name: set timezone
      shell: timedatectl set-timezone Asia/Kolkata

    - name: Install NTP
      yum: 
        name: ntp
        state: present

    - name: start ntp
      service:
        name: ntpd
        state: started
        enabled: true

    - name: allow ntp through firewall
      shell: firewall-cmd --add-service=ntp --permanent

    - name: firewall reload
      shell: firewall-cmd --reload
 
    - name: Copy over the NTP configuration
      template: src=/home/avinash/itversity/task2//work/ntp_data/slave/ntp.conf dest=/etc/ntp.conf

    - name: restart ntpd
      service:
        name: ntpd
        state: restarted      
 
    - name: Make sure NTP is stopped
      service: 
        name: ntpd 
        state: stopped 
        enabled: true
        
    - name: Sync time initialy
      shell: ntpdate 192.168.10.210
      

    - name: Make sure NTP is started up
      service: 
        name: ntpd 
        state: restarted 
        enabled: true
     
    - name: Sync hwclock
      shell: hwclock -w
      tags: ntp

    - name: restart ntpd
      service: 
        name: ntpd 
        state: restarted
