---
- hosts: master
  tasks:
    - name: install java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Creating a repository file for cassandra_db
      file:
        path: /etc/yum.repos.d/cassandra.repo
        state: touch

    - name: insert repo data in cassandra.repo
      blockinfile:
        path: /etc/yum.repos.d/cassandra.repo
        block: |
          [cassandra]
          name=Apache Cassandra
          baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://www.apache.org/dist/cassandra/KEYS
   
    - name: install cassandra database
      yum:
        name: cassandra
        state: latest
        #    - name: update config file
        # copy:
        #src: /home/avinash/itversity/task2/work/cassendra_db/cassandra_master.yml
        #dest: /etc/cassandra/conf/cassandra.yaml
    - name: enable the service cassandra.
      service:
        name: cassandra
        state: started
        enabled: true
        # - name: allow cassandra through firewall
        #firewalld:
        #service: cassandra
        #state: enabled
        #permanent: yes

        # - name: firewall reload
        # service:
        #name: firewalld
        #state: reloaded

